- os_network:
    cloud: ospcloud
    state: present
    name: ext_network
    external: true
    admin_state_up: yes
    provider_network_type: flat
    provider_physical_network: datacentre
    
- os_subnet:
    cloud: ospcloud
    state: present
    network_name: ext_network
    name: ext_subnet
    cidr: "192.0.2.0/24"
    ip_version: 4
    gateway_ip: "192.0.2.254"
    enable_dhcp: no
    allocation_pool_start: 192.0.2.150
    allocation_pool_end: 192.0.2.200
    dns_nameservers:
      - 8.8.8.8
      - 8.8.8.7

- os_network:
    cloud: ospcloud
    state: present
    name: int_network
    external: false
    admin_state_up: yes
    
- os_subnet:
    cloud: ospcloud
    state: present
    network_name: int_network
    name: int_subnet
    cidr: "172.16.0.0/24"
    ip_version: 4
    enable_dhcp: yes
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8

- os_router:
    cloud: ospcloud
    state: present
    name: router
    network: ext_network
    external_fixed_ips:
      - subnet: ext_subnet
    interfaces:
      - int_subnet
