- name: In momory inventory play
  hosts: all
  gather_facts: False
  tasks:  
  - name: Fetch Instance Info
    os_server_info:
      region_name: regionOne
    register: result

  - name: Add host
    add_host:
      name: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
    with_items: "{{result.openstack_servers}}"

  - debug: var=groups
